### PR TITLE
Adjusted to support compilation on UB CCR supercomputer using intel a…

### PR DESCRIPTION
**Pull request by lsmatott**
…nd intel-mpi.

### CODE REVIEW

**Comment by dloney** [comment]
I'm going to merge these in. I've halted development on the master while getting the algorithms into dev. @lsmatott Do you want to make the same compiler changes on dev as well?

**Comment by dloney** [comment]
Should we try to avoid putting hardware specific files into the repo? I don't think this generalizes across all the different machines that folks are using. Otherwise we might need to create a separate folder in the make structure to support specific machines.

**Comment by lsmatott** [comment]
I’ve seen other projects provide a general makefile/build setup and then a bunch of alternatives (e.g. for different flavors of Linux). Perhaps something like that for the different hpc centers is needed. So ubcc-build.sh and makefile.ubccr, osc-build.sh and makefile.osc --- what do you think?

--- Shawn

From: Drew Allan Loney ***@***.***>
Date: Friday, January 7, 2022 at 9:17 AM
To: usbr/ostrich ***@***.***>
Cc: Loren Matott ***@***.***>, Mention ***@***.***>
Subject: Re: [usbr/ostrich] Adjusted to support compilation on UB CCR supercomputer using intel a… (PR #35)

Should we try to avoid putting hardware specific files into the repo? I don't think this generalizes across all the different machines that folks are using. Otherwise we might need to create a separate folder in the make structure to support specific machines.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusbr%2Fostrich%2Fpull%2F35%23issuecomment-1007440200&data=04%7C01%7Clsmatott%40buffalo.edu%7C7dc135933005497480d008d9d1e88247%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771618769932802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=MKvJuhjzEmYGkHGUo2X0Im7GddyR%2BvO4cCaMVIjfnoM%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB6LJVAPBQISTNWMZEWTM5DUU3YZNANCNFSM5HJ7CGSQ&data=04%7C01%7Clsmatott%40buffalo.edu%7C7dc135933005497480d008d9d1e88247%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771618769932802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8cynofedO%2BfyyFx25301cZowy3H3OFqWbt3obNgpqp8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clsmatott%40buffalo.edu%7C7dc135933005497480d008d9d1e88247%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771618769932802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NYWzYDuMPyDuH1T3Yez5FDoWrxzQlmA8U9tVSTgElNo%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clsmatott%40buffalo.edu%7C7dc135933005497480d008d9d1e88247%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771618769932802%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=M3zzSd0oyleSGzseRvSBzJ0OQnwCT%2Fj4Wme63psgy48%3D&reserved=0>.

**Comment by dloney** [comment]
The clearer naming works for me. We did something similar for Proteus on the DoD HPCs, then folks working on those specific machines could take ownership of keeping the build scripts up-to-date. Folks who didn't care about the other machines could essentially ignore the file. On USGS Denali, I've been manually changing the make file.

As an aside, I'm enforcing a C++17 standard on dev, mostly for the filesystem library. It might be good to add in to platform specific make files if we're doing modifications.

**Comment by lsmatott** [comment]
Ok – next time I commit I will start using platform-specific make and build files.

--- Shawn

From: Drew Allan Loney ***@***.***>
Date: Friday, January 7, 2022 at 9:46 AM
To: usbr/ostrich ***@***.***>
Cc: Loren Matott ***@***.***>, Mention ***@***.***>
Subject: Re: [usbr/ostrich] Adjusted to support compilation on UB CCR supercomputer using intel a… (PR #35)

The clearer naming works for me. We did something similar for Proteus on the DoD HPCs, then folks working on those specific machines could take ownership of keeping the build scripts up-to-date. Folks who didn't care about the other machines could essentially ignore the file. On USGS Denali, I've been manually changing the make file.

As an aside, I'm enforcing a C++17 standard on dev, mostly for the filesystem library. It might be good to add in to platform specific make files if we're doing modifications.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fusbr%2Fostrich%2Fpull%2F35%23issuecomment-1007463126&data=04%7C01%7Clsmatott%40buffalo.edu%7C58492fcd8d204ca0641208d9d1ec76e7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771635829587605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=lwGpamQNBR3vjEG%2FGEnxsxS%2BvODTJ96fT0c9MDXdhzc%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAB6LJVBPK2KVXS4IVGZTBFTUU34DVANCNFSM5HJ7CGSQ&data=04%7C01%7Clsmatott%40buffalo.edu%7C58492fcd8d204ca0641208d9d1ec76e7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771635829587605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XLKMt4I75YNG29E9t%2F2iRIBL%2FtnX9d2khdgNBfaFrKo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clsmatott%40buffalo.edu%7C58492fcd8d204ca0641208d9d1ec76e7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771635829746915%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=kjz9OnMbQQ7ygC1SuaSDnnPo7yqwykVEFZUiO44jM5Y%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clsmatott%40buffalo.edu%7C58492fcd8d204ca0641208d9d1ec76e7%7C96464a8af8ed40b199e25f6b50a20250%7C0%7C0%7C637771635829746915%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2BH%2FDfYlicf5SZLrutecLIsE07EbSIe6atajDUIiOuNw%3D&reserved=0>.

**Pull request merged**
