### PR TITLE
Lsmatott

### PR DESCRIPTION
**Pull request by dloney**
Requesting approval from @lsmatott  to make sure these are the most recent changes to the branch.

### CODE REVIEW

**Comment by dloney** [comment]
Quick questions so I understand the intent of the changes. Is there a reason to still support GCC5? I'm surprised that even works with the C++17 filesystem dependencies.

You've added components for the parameter initialization. Is that something that would make more sense to add to the dev branch, rather than adding functionality into the old codebase? Otherwise it will add to items that need to be migrated to dev in the future before the full change over.

**Comment by lsmatott** [comment]
HI Drew,

The dev branch has reduced functionality relative to the main branch - is that correct?

Thanks,

--- Shawn

**Comment by dloney** [comment]
That's correct. I've been migrating algorithms to the new MPI engine as I get the bandwidth to do so.

**Comment by lsmatott** [comment]
Ok - my changes are in support of some research projects underway at UB. It will require working versions of basically all of the optimization algorithms, including parallel functionality, so working from a branch of the main repo seems like the most convenient choice. The good news is that they won't be using GML and that seems to have been the focus of the "dev" branch so far.

Is there a command I can run to identify merge conflicts between "lsmatott" and "dev" branches?

Also, what is the new MPI engine?

Thanks,

---- Shawn

**Comment by dloney** [comment]
I thought we were going to transition to forking workflow to better manage merge conflicts.

The current version of Ostrich replicates the full version of memory and algorithm space between all workers and synchronizes the full results between all of them. That's not memory/compute efficient and isn't scalable. It also requires custom MPI logic within each algorithm. 

The MPI engine on dev sets up a primary and secondary worker configuration. The primary worker has the algorithm logic and the secondary workers have just enough logic to do the model solves. That decouples the MPI logic from the algorithm logic, reducing the memory and compute usage. It also allows for reuse of the MPI solver logic. If the changes you're planning to make are going to be that extensive across all the algorithms, I'd recommend doing them on dev.

**Comment by dloney** [comment]
If you make a fork of the project, you should get this branch to come with it. You should be able to check the branch back out and make pull requests back into this repository.

I'm not opposed to adding new features into the current code base, but we should mirror the functionality over onto dev so we can enable the future transition to dev.

**Comment by lsmatott** [comment]
Hi Drew,

Sounds like a plan --- I'll fork the project this weekend and start using that approach.

Should I manually mirror the functionality in the dev branch of my fork? Or is that something that git commands can help with?

Thanks,

--- Shawn

**Pull request closed without merging**
